### ISSUE TITLE
Parsing exception when last chunk header is truncated/missing

### ISSUE THREAD

**Issue by neroux** [oblac/jodd-http#1]
@igr, please take this with a grain of salt as **I can't yet really say if this is a Jodd issue or not**.

The only thing I noticed is that I relatively often the [`Invalid chunk length: null` exception](https://github.com/oblac/jodd-http/blob/720a304ee8db25429c69922b21f6587e0a408dc4/src/main/java/jodd/http/HttpBase.java#L1009) or SSL exceptions when using Jodd on Android.

This primarily (and most often) happens on the emulator, however, less regularly also on actual devices. Usually I'd dismiss this as an occasional network glitch and the only reason why I'd even consider it could be a Jodd issue is that it happens across different URLs _(if it was just one I'd say that server's SSL stack is corrupt)_ and I don't seem to experience these issues with other HTTP libraries (currently also evaluating Google's Volley).

I am not sure either yet, if the chunk and the SSL exceptions are related, but my guess would be rather yes and the chunk issue shows up because something is off with the SSL layer. AFAIK you are not just using the default socket factory for Jodd but have something custom, is that right? In that case could there be something that Android occasionally does not like?

**Comment by neroux** [comment]
I have observed the issue already for a few months but always attributed it to the webserver. I am bringing this up only now because I have only noticed now that it happens across different webservers and that would rather suggest a client-side issue. I have spent the last hour debugging it and unfortunately it is extremely random and erratic. Works fine for five requests and then there are suddenly a couple where I get a null chunk.

The reason why I am more and more convinced this is a Jodd issue is that it only happens with jodd-http. The moment I switch to e.g. OkHttp I consistently get the right response

```java
new OkHttpClient().newCall(
	new Request.Builder().url(
		HttpUrl.parse("URL").newBuilder()
			.addQueryParameter("p1", "v1")
			.addQueryParameter("p2", "v2")
			.build()
	).build()
).execute();
```

against

```java
HttpRequest.get("URL")
	.query("p1", "v1", "p2", "v2")
	.send();
```

_Incidentially, these two code samples also show the beauty of Jodd. And no, that call cascade with OkHttp is not because of my inexperience with OkHttp :) -> https://stackoverflow.com/questions/30142626/how-to-add-query-parameters-to-a-http-get-request-by-okhttp_

I should also mention, that it probably is not only Android related as I get the same null chunk error also with a Groovy project which runs on a normal JRE, though still very rarely. Only the Android emulator throws that error somewhat regularly.

**Comment by igr** [comment]
Hum, maybe the chunk was really `null` and jodd may continue, assuming it's just an 'empty' chunk.

If I make a SNAPSHOT, would you be able to use it?

Regarding SSL exceptions (writing here as it might help someone) :

```java
SocketHttpConnectionProvider socketHttpConProvider = new SocketHttpConnectionProvider();
socketHttpConProvider.setSslProtocol("TLSv1.2");
    
HttpRequest httpRequest = HttpRequest.post(service).withConnectionProvider(socketHttpConProvider);
HttpResponse httpResponse = httpRequest.send();
```

**Comment by igr** [comment]
(that was the whole idea for jodd HTTP, easy of use and no magic behind, but there are sooo many cases that need to be caught)

**Comment by neroux** [comment]
> Hum, maybe the chunk was really `null`

That was my original assumption. The site where I experienced it is not handled by the most competent group of people, so I assumed that was just yet another glitch.

However, in my new project it happens across a number of sites and - and that's my primary reason why I am currently pointing at Jodd - these issues seem to disappear the second I switch to something like OkHttp or Volley.

Again, please do take the whole thing with a grain of salt but when I ran yesterday several tests, I could reproduce it quite well with Jodd (though again, not 100% of the times - the issue shows up for X requests and then disappears for Y requests, only to show up again) however when running the same number of tests with OkHttp not a single request failed. That's the only reason why I even consider the possibility of the issue being with Jodd.

> If I make a SNAPSHOT, would you be able to use it?

Sure. What would you be thinking of changing here?

> Regarding SSL exceptions (writing here as it might help someone) :

Unfortunately I don't have the exact stack trace right here, but the message refers to a broken SSL channel. I will update the thread once I come across it again.

I assume 1.2 is currently enabled, right? So that connection provider would only allow 1.2 and disable older versions?

**The whole issue is admittedly somewhat obscure.**

**Comment by igr** [comment]
> Sure. What would you be thinking of changing here?

The message of the exception is just fine, it says that `read()` returned `null`. What I can do is try to re-read the data from the socket, i.e. to treat like `0` bytes is sent. That's I guess the simplest way I can fix the NPE.

**Comment by neroux** [comment]
Okay, got it. I am just not sure if the problem is with the HTTP part of Jodd and not rather with the SSL layer in-between.

Again, I am afraid the whole thing seems obscure for the time being and does not seem to be deterministically reproducible.

**Comment by neroux** [comment]
_Just some update on the record for future readers (as some details were exchanged in private)_

The issue does not appear to be reproducible with a regular Intel JVM (at least not as consistently as on Android) and a current snapshot of v6.0.3 (where `BufferedReader.readLine()` is called more than once) seems to mitigate the issue.

So far I seem to be able to confirm that the issue only happens on HTTPS and not HTTP, which would point at the underlying SSL layer. Furthermore it seems as if the request size (e.g. the query string) would also play a factor on whether the error occurs or not.

**Comment by neroux** [comment]
> where `BufferedReader.readLine()` is called more than once

My apologies, that was an incorrect assumption. The fix does not call `readLine` more than once but defaults to zero if the chunk length cannot be determined.

That actually seems to do the trick and I couldn't reproduce the error any more with 6.0.3, however I still can't explain why the error was seemingly only thrown on HTTPS but not on HTTP (which is also the reason for the title).

I'll run more tests with 6.0.3 but if the issue does not occur any longer, we can close this issue and I should update the title.

**Comment by neroux** [comment]
> that was the whole idea for jodd HTTP, easy of use and no magic behind

I can really only emphasise this once more

```java
new OkHttpClient().newCall(
	new Request.Builder().url(
		HttpUrl.parse("URL").newBuilder()
			.addQueryParameter("p1", "v1")
			.addQueryParameter("p2", "v2")
			.build()
	).build()
).execute();
```

against

```java
HttpRequest.get("URL")
	.query("p1", "v1", "p2", "v2")
	.send();
```

It is amazing that a popular library like OkHttp makes you jump through all these hoops for something which you can achieve with a one-liner with Jodd. And it does not even provide more flexibility. Jodd equally allows to tamper with individual requests like (e.g. the `path` method).

That's not abstracting things any more, that's just a good example for over-engineering. Sorry for the rant :)

**Comment by igr** [comment]
Released v6.0.3 with the fix :)

**Comment by neroux** [comment]
Renamed the issue. I still have occasional SSL errors but defaulting to 0 seems to have fixed something.

I am still puzzled why it seemingly only occured on HTTPS and not HTTP but lacking a way to consistently reproduce it, it is difficult to debug so I'll let it be :)

Thanks again 🙇🏻‍♂️

**Comment by igr** [comment]
Hey, no problem!

When you get the next SSL error, just please make a new Issue here, maybe we can figure out whats wrong :)
