### ISSUE TITLE
Relative Location URL not always handled properly

### ISSUE THREAD

**Issue by neroux** [oblac/jodd-http#10]
It would seem as if `HttpResponse.location()` did not always assemble the correct URL.

https://github.com/oblac/jodd-http/blob/720a304ee8db25429c69922b21f6587e0a408dc4/src/main/java/jodd/http/HttpResponse.java#L90-L102

It will treat `Location` only as relative URL if it starts with a slash, otherwise it will always consider it as absolute URL, which is not necessarily correct, however.

See https://datatracker.ietf.org/doc/html/rfc3986#section-4.2 please

> A relative reference that does not begin with a slash character is termed a relative-path reference.

[`java.net.URL()`](https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#URL(java.net.URL,%20java.lang.String)) might help in that case.

```java
new URL(new URL(httpRequest.url()), location)
```

**Comment by igr** [comment]
I believe this part helps:

> A path segment that contains a colon character (e.g., "this:that") cannot be used as the first segment of a relative-path reference, as it would be mistaken for a scheme name.  Such a segment must be preceded by a dot-segment (e.g.,"./this:that") to make a relative-path reference.

as we can inspect if there is a column before the first slash

**Comment by neroux** [comment]
That would only apply to paths with a colon character.

But why do you think `URL` wouldn't work?

**Comment by neroux** [comment]
That refers to a different issue, however. The issue here are relative paths.

But why do you think URL wouldn't work?

**Comment by igr** [comment]
> That would only apply to paths with a colon character.

the logic I figured from the rfc is this: if there is a `:` in the first segment, then it is an absolute URL. Otherwise, it is a relative URL.

``` java
		assertFalse(HttpUtil.isAbsoluteUrl("just/a/path"));
		assertFalse(HttpUtil.isAbsoluteUrl("/just/a/path"));
		assertFalse(HttpUtil.isAbsoluteUrl("/ju:st/a/path"));

		assertTrue(HttpUtil.isAbsoluteUrl("ju:st/a/path"));
```

Just want to optimize the process and skip the URL creation :)

**Comment by neroux** [comment]
Gotcha.

Though, `ju:st/a/path` would simply not be a valid value anyhow.

As far as I can tell you really don't need to run any validation here. `java.net.URL` should cover that. Would you want me to send a PR?

**Comment by neroux** [comment]
All right, you are trying to avoid using `URL` then.

In that case, yes, I believe your summary is correct, though I'd probably still use `URL`. I don't think it should be a performance issue in this context and may address edge cases which we are not even discussing here.

**Comment by igr** [comment]
I just really tried to get away from the URL :) Last time when I was checking, just parsing the string took a crazy amount of time.

**Comment by neroux** [comment]
I understand that, but as mentioned I am not sure performance really is a key factor here :)

Also, did you test this? I somehow have the impression that might still be buggy, especially with with existing paths and possibly missing trailing slashes. Hence why I suggested `URL` :)

**Comment by neroux** [comment]
@igr, yes, I am afraid it's still not fixed.

Sending a path like `../file.txt` will still not work. I'd still strongly recommend `URL` :)

**Comment by igr** [comment]
You are right, it is too much to cover.

**Comment by igr** [comment]
I would need to create a similar method to `FilenameUtil` for the URLs...

**Comment by igr** [comment]
Thank you very much for being the second pair of eyes!!! (sorry for the late response, it was my week after vacation)

**Comment by neroux** [comment]
Hi @igr,

I have to say sorry for bothering you during your vacation :)

Unfortunately I am not sure if the current implementation is fully compliant either. Mostly because you still have the `isAbsoluteUrl()` check in there, which will still return `false` for the URL example `this:that` mentioned earlier.

I'd probably drop the `isAbsoluteUrl()` and fully rely on `URL` :)

**Comment by neroux** [comment]
I hope you had a nice vacation however :)

**Comment by neroux** [comment]
Hi @igr,

I have to say sorry for bothering you during your vacation :)

I think it should now work, even though the current implementation may not be fully compliant either, because `isAbsoluteUrl()` will still return `false` for the URL metioned earlier, `this:that`. However, considering it will then use `URL` anyhow, it should work.

Hope you had a great vacation :)

**Comment by igr** [comment]
No worries at all!

Wait, you meant to replace whole the `if` block with `URL..URL..` piece of code?

**Comment by igr** [comment]
Yeah, you are right - no need to do that at all! Awesome!

**Comment by igr** [comment]
Feel free to check, and then I will release the new version @neroux

**Comment by neroux** [comment]
@igr, apologies for the delayed reply, I thought I had replied and only realised now I had not. My bad 😳

Yeah, I guess it should work fine now. 

I'd probably just adjust the JavaDoc. Maybe something along these lines.

```
	/**
	 * Parses the 'location' header and returns an absolute URL for the provided path. Returns {@code null}
	 * if no location was specified or throws {@code HttpException} if it was impossible to assemble a valid URL.
	 *
	 * RFC 2616 still required an absolute URL, whereas RFC 9110 introduced the support for relative paths.
	 */
```

**Comment by igr** [comment]
Beautiful! Will release it now!
