### ISSUE TITLE
Missing Java 7 SSL method on Android 6 and below

### ISSUE THREAD

**Issue by neroux** [oblac/jodd-http#3]
Hi Igor,

Just a heads-up that Jodd HTTP won't work on Android 6 (Android API level 23) and lower (at least if HTTPS URLs are being used) because these versions do not seem to use [Java 1.7 yet and hence do not have `javax.net.ssl.SSLParameters.setEndpointIdentificationAlgorithm()`](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm(java.lang.String)), which is used by `jodd.http.net.SocketHttpConnectionProvider.createSSLSocket()`

https://github.com/oblac/jodd-http/blob/720a304ee8db25429c69922b21f6587e0a408dc4/src/main/java/jodd/http/net/SocketHttpConnectionProvider.java#L221

Trying to load an HTTPS URL will throw a `NoSuchMethodError` error

    java.lang.NoSuchMethodError: No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)
        at jodd.http.net.SocketHttpConnectionProvider.createSSLSocket(SocketHttpConnectionProvider.java:221)
        at jodd.http.net.SocketHttpConnectionProvider.createHttpConnection(SocketHttpConnectionProvider.java:99)
        at jodd.http.HttpRequest.open(HttpRequest.java:775)
        at jodd.http.HttpRequest.open(HttpRequest.java:759)
        at jodd.http.HttpRequest._send(HttpRequest.java:887)
        at jodd.http.HttpRequest.send(HttpRequest.java:853)

This is not so much of a bug report but really rather just of informative nature. Of course it would be great if it worked on 6 and below as well, but at a market share of about 12% and dropping it is questionable whether the effort will be worth it.

**Comment by igr** [comment]
As Jodd6 is Java8+ only, closing this issue.

**Comment by neroux** [comment]
The problem is not the Java version per se, but rather that the method in question is not present up to Marshmallow.

As I mentioned, about 90% are Nougat+ already but it's still something to keep in mind that the library won't really work up to API level 23.
