### ISSUE TITLE
NullPointer on missing Location header

### ISSUE THREAD

**Issue by neroux** [oblac/jodd-http#5]
Hi @igr,

I just got the following stacktrace.

    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
           at jodd.http.HttpRequest.set(HttpRequest.java)
           at jodd.http.HttpRequest.send(HttpRequest.java:36)

The issue seems to have been that Jodd understood it received a redirect but apparently did not receive a `Location` header, hence it passed `null` to `set()` which then threw a `NullPointer`

https://github.com/oblac/jodd-http/blob/d359c65441d71d934df3e40a6d1a51d8339b21a6/src/main/java/jodd/http/HttpRequest.java#L888

It would appear as if `Location` was [not sent with all 300s](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location#see_also), and even then, it actually seems to be an [optional header in **general**](https://stackoverflow.com/questions/16194988/for-which-3xx-http-codes-is-the-location-header-mandatory/37101262).

**Comment by igr** [comment]
I assume we may stop with the redirection (as no Location is set) and return the response?

Thank you for reporting!

**Comment by neroux** [comment]
> I assume we may stop with the redirection (as no Location is set) and return the response?

Either that or throw an `HttpException`, similar to https://github.com/oblac/jodd-http/blob/d359c65441d71d934df3e40a6d1a51d8339b21a6/src/main/java/jodd/http/HttpRequest.java#L895

I guess I slightly prefer _stopping and returning the response_ as there was no error per se (the header is not required), on the other hand one might argue he wouldn't expect a 300 response when `followRedirects` is `true`.

Both are valid point of views IMHO, though I'd still tend to go more with _stop and return_.

**Comment by igr** [comment]
Agree, this was a valid state, hence we should break the loop. Yap!

**Comment by igr** [comment]
6.0.8. released :)

**Comment by neroux** [comment]
Thanks 🥳
