### ISSUE TITLE
Chunked and non-chunked responses handled differently

### ISSUE THREAD

**Issue by neroux** [oblac/jodd-http#6]
Hi @igr,

`java.jodd.http.HttpBase.readBody()` seems to behave differently for chunked and non-chunked encodings.

When there is a zero-byte non-chunked response, `readBody` won't even try to read anything and `bodyString` will stay `null`.

https://github.com/oblac/jodd-http/blob/f8475c7d1990c334ca406502fef9832c3a5c26db/src/main/java/jodd/http/HttpBase.java#L983-L993

Whereas, when a zero-byte chunked response is sent, `bodyString` will always be set to non-null value.

https://github.com/oblac/jodd-http/blob/f8475c7d1990c334ca406502fef9832c3a5c26db/src/main/java/jodd/http/HttpBase.java#L999-L1031

**Comment by neroux** [comment]
I'd say skipping the `if` might be the most straightforward "fix".

https://github.com/oblac/jodd-http/blob/f8475c7d1990c334ca406502fef9832c3a5c26db/src/main/java/jodd/http/HttpBase.java#L983

In that case `bodyString` will always be populate and the behaviour would be identical.

Only the JavaDoc would need a slight rewording

https://github.com/oblac/jodd-http/blob/f8475c7d1990c334ca406502fef9832c3a5c26db/src/main/java/jodd/http/HttpBase.java#L618

**Comment by igr** [comment]
Yap, you are right. I will just add `else` to minimize the resource usage in case body is 0 length!

Thank you!!!

**Comment by igr** [comment]
I will wait for couple of days to resolve the jodd-util upgrade, and then bump this library.

**Comment by neroux** [comment]
Hi @igr, possibly any update on when this will be available?

Also, while the documentation does not refer to `null` any more, it still does return `null`.

https://github.com/oblac/jodd-http/blob/485044d7b1c0bfb323e4e868ca94e7babfa28617/src/main/java/jodd/http/HttpBase.java#L618-L623

Thanks.

**Comment by igr** [comment]
In fact very soon, I have sorted out the jodd-util upgrade, so my plan is to publish it tomorrow!

**Comment by neroux** [comment]
Одлично, хвала 🙂
